//<auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Xml.Serialization;

namespace YYhUpload.Model
{
    /// <summary>
    /// 将泛型对象翻译为xml
    /// </summary>
    /// <typeparam name="T"></typeparam>
    [Serializable()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false, ElementName = "datasets")]
    public class BusinessDateSets<T> 
    {
        public string setcode { get; set; } = "";
        public string settype { get; set; } = "";
        [XmlElement()]
        public List<T> setdetails { get; set; }
    }

    [Serializable()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false, ElementName = "dmp")]
    public class BusinessData<T>
    {
        public BusinessDateSets<T> datasets { get; set; }
    }
}
