//<auto-generated>

using YYhUpload.Model;

namespace Fy3y.Model.YYH
{
    /// <summary>
    /// 门急诊常规报告
    /// </summary>
    public class Mjz_Jycgbg:YYhBase
    {
        /// <summary>
        /// 本人姓名本人在公安管理部门正式登记注册的姓氏和名称
        /// 是否必填：Y
        /// </summary>
        public string WS02_01_039_001 { get; set; }
        /// <summary>
        /// 性别代码本人生理性别的代码
        /// 1、在【GB/T2261.1人的性别代码】值域范围内，且与【性别名称】匹配
        /// </summary>
        public string WS02_01_040_01 { get; set; }
        /// <summary>
        /// 性别名称本人生理性别的名称
        /// </summary>
        public string CT02_01_040_01 { get; set; }
        /// <summary>
        /// 年龄(岁)患者年龄满1周岁的实足年龄，为患者出生后按照日历计算的历法年龄，以实足年龄的相应整数填写
        /// 1、类型为数值
        /// </summary>
        public string WS02_01_026_01 { get; set; }
        /// <summary>
        /// 年龄(月)年龄不足1周岁的实足年龄的月龄，以分数形式表示：分数的整数部分代表实足月龄，分数部分分母为30，分子为不足1个月的天数（例如12/30）个月的天数（例如12/30）
        /// </summary>
        public string WS02_01_032_02 { get; set; }
        /// <summary>
        /// 门(急)诊号按照某一特定编码规则赋予门（急）诊就诊对象的顺序号（唯一标识一次门急诊业务，若机构的门诊号采取循环序列，则可联合挂号时间唯一确定一次业务）
        /// 是否必填：Y
        /// </summary>
        public string WS01_00_010_01 { get; set; }

        /// <summary>
        /// 身份证件类别代码本人身份证件类别的代码1、在【CV02.01.101身份证件类别代码表】值域范围内，且与【身份证件类别名称】匹配
        /// 是否必填：Y
        /// </summary>
        public string WS02_01_031_01 { get; set; } = "01";

        /// <summary>
        /// 身份证件类别名称本人身份证件类别的名称
        /// 是否必填：Y
        /// </summary>
        public string CT02_01_031_01 { get; set; } = "居民身份证";
        /// <summary>
        /// 身份证号码身份证上唯一的法定标识符
        /// 是否必填：Y
        /// </summary>
        public string WS02_01_906_01 { get; set; }

        /// <summary>
        /// 患者ID	患者在医院内部的唯一编号
        /// </summary>
        public string WS99_99_999_16 { get; set; }
        /// <summary>
        /// 电子申请单编号按照某一特定编码规则赋予电子申请单的顺序号
        /// 是否必填：Y
        /// </summary>
        public string WS01_00_008_03 { get; set; }
        /// <summary>
        /// 报告单编号按照某一特定编码规则赋予报告单的顺序号
        /// 是否必填：Y
        /// </summary>
        public string WS01_00_018_01 { get; set; }
        /// <summary>
        /// 项目序号用于描述本条记录的排列顺序号码
        /// 是否必填：Y
        /// </summary>
        public string WS01_00_907_01 { get; set; }
        /// <summary>
        /// 检查/检验项目编码受检者检查/检验项目在特定编码体系中的编码,如LOINC 的代码值
        /// 是否必填：Y
        /// </summary>
        public string WS04_30_019_01 { get; set; }
        /// <summary>
        /// 检查/检验项目名称检查报告项目的名称
        /// 是否必填：Y
        /// </summary>
        public string WS04_30_020_01 { get; set; }
        /// <summary>
        /// 申请项目代码申请检查项目在机构诊疗项目目录中的编码
        /// </summary>
        public string WS02_10_916_01 { get; set; }
        /// <summary>
        /// 申请项目名称申请检查项目的名称
        /// </summary>
        public string WS02_10_916_02 { get; set; }
        /// <summary>
        /// 检验结果（数值）患者检验结果数值
        /// </summary>
        public string WS04_30_009_03 { get; set; }
        /// <summary>
        /// 临床意义对该检验项目在临床上的意义和医生建议的描述
        /// </summary>
        public string WS05_01_904_02 { get; set; }
        /// <summary>
        /// 危急值标志危急值标志
        /// 1、类型为数值1、在【CT05.01.001是否代码】值域范围内
        /// </summary>
        public string WS05_10_926_01 { get; set; }
        /// <summary>
        /// 检验结果代码检验结果代码 （1 正常；2异常）
        /// 1、在【CT04.30.001正异结果代码】值域范围内
        /// </summary>
        public string WS04_30_009_06 { get; set; }
        /// <summary>
        /// 仪器编码检验仪器编码
        /// </summary>
        public string WS04_30_023_04 { get; set; }
        /// <summary>
        /// 仪器名称检验仪器名称
        /// </summary>
        public string WS04_30_023_05 { get; set; }
        /// <summary>
        /// 计量单位受检者定量检查/检验结果测量值的计量单位
        /// </summary>
        public string WS04_30_016_01 { get; set; }
        /// <summary>
        /// 检验结果描述对检验结果的详细描述
        /// </summary>
        public string WS04_50_913_01 { get; set; }
        /// <summary>
        /// 参考值检验结果在合理区间内的参数
        /// </summary>
        public string WS04_50_902_01 { get; set; }
        /// <summary>
        /// 异常结果每一项检验结果的异常信息，如：上下箭头、加减号、H、L 等偏差异常结果的表示符号
        /// </summary>
        public string WS04_10_903_01 { get; set; }
        /// <summary>
        /// 检查、检验方法患者接受医学检查项目所采用的检查方法
        /// </summary>
        public string WS02_10_027_01 { get; set; }
        /// <summary>
        /// 报告机构代码,出具检查、检验的报告单的医疗机构的代码1、在【CT99.00.001机构代码（本地化）】值域范围内，且与【报告机构名称】匹配
        /// 是否必填：Y
        /// </summary>
        public string WS08_10_052_03 { get; set; }
        /// <summary>
        /// 报告机构名称-出具检查、检验的报告单的医疗机构的名称
        /// 是否必填：Y
        /// </summary>
        public string CT08_10_052_03 { get; set; }
        /// <summary>
        /// 报告日期时间-生成报告的当日的公元纪年日期和时间1、符合【yyyyMMddHHmmss】的格式
        /// 是否必填：Y
        /// </summary>
        public string WS06_00_926_01 { get; set; }
        /// <summary>
        /// 检验互认编码
        /// </summary>
        public string WS99_99_999_17 { get; set; }
        /// <summary>
        /// 结果正常标志
        /// </summary>
        public string WS99_99_999_19 { get; set; }

        /// <summary>
        /// 检验日期时间
        /// </summary>
        public string WS06_00_925_01 { get; set; }
        /// <summary>
        /// CA签名值最后一名签名医生（护士）的CA医生签名
        /// 1、门(急)诊检验报告有CA签名可不填
        /// </summary>
        public string WS99_99_010_48 { get; set; }
    }
}
