//<auto-generated>
using YYhUpload.Model;
namespace Fy3y.Model.YYH
{
    /// <summary>
    /// 门急诊检验报告
    /// </summary>
    public class Mjz_Jybg:YYhBase
    {
        /// <summary>
        /// 本人姓名
        /// </summary>
        public string WS02_01_039_001 { get; set; }
        /// <summary>
        /// 性别代码
        /// </summary>
        public string WS02_01_040_01 { get; set; }
        /// <summary>
        /// 性别名称
        /// </summary>
        public string CT02_01_040_01 { get; set; }
        /// <summary>
        /// 年龄(岁)
        /// </summary>
        public string WS02_01_026_01 { get; set; }
        /// <summary>
        /// 年龄(月)
        /// </summary>
        public string WS02_01_032_02 { get; set; }
        /// <summary>
        /// 年龄(日)
        /// </summary>
        public string WS99_99_026_01 { get; set; }
        /// <summary>
        /// 年龄（小时）
        /// </summary>
        public string WS99_99_026_02 { get; set; }
        /// <summary>
        ///  就诊卡号
        /// </summary>
        public string WS99_99_903_40 { get; set; }
        /// <summary>
        /// 卡类型代码
        /// </summary>
        public string WS99_99_902_07 { get; set; }
        /// <summary>
        /// 卡类型名称
        /// </summary>
        public string CT99_99_902_07 { get; set; }
        /// <summary>
        /// 患者ID	患者在医院内部的唯一编号
        /// </summary>
        public string WS99_99_999_16 { get; set; }
        /// <summary>
        /// 患者类型代码
        /// </summary>
        public string WS02_01_060_01 { get; set; }
        /// <summary>
        /// 患者类型名称
        /// </summary>
        public string CT02_01_060_01 { get; set; }
        /// <summary>
        /// 出生日期
        /// </summary>
        public string WS02_01_005_01_01 { get; set; }

        /// <summary>
        /// 身份证件类别代码
        /// </summary>
        public string WS02_01_031_01 { get; set; } = "01";

        /// <summary>
        /// 身份证件类别名称
        /// </summary>
        public string CT02_01_031_01 { get; set; } = "居民身份证";
        /// <summary>
        ///  身份证件号码
        /// </summary>
        public string WS02_01_030_01 { get; set; }
        /// <summary>
        /// 门(急)诊号
        /// </summary>
        public string WS01_00_010_01 { get; set; }
        /// <summary>
        /// 电子申请单编号
        /// </summary>
        public string WS01_00_008_03 { get; set; }
        /// <summary>
        /// 报告单编号
        /// </summary>
        public string WS01_00_018_01 { get; set; }
        /// <summary>
        /// 报告单名称
        /// </summary>
        public string WS01_00_900_02 { get; set; }

        /// <summary>
        /// 报告单类别代码
        /// </summary>
        public string WS01_00_900_01 { get; set; } = "2";

        /// <summary>
        /// 报告单类别名称
        /// </summary>
        public string CT01_00_900_01 { get; set; } = "最终报告";
        /// <summary>
        /// 申请项目代码
        /// </summary>
        public string WS02_10_916_01 { get; set; }
        /// <summary>
        /// 申请项目名称
        /// </summary>
        public string WS02_10_916_02 { get; set; }
        /// <summary>
        /// 标本类别代码
        /// </summary>
        public string WS04_50_134_01 { get; set; }
        /// <summary>
        /// 标本类别名称
        /// </summary>
        public string CT04_50_134_01 { get; set; }
        /// <summary>
        /// 院内标本类别代码
        /// </summary>
        public string WS99_99_902_128 { get; set; }
        /// <summary>
        /// 院内标本类别名称
        /// </summary>
        public string CT99_99_902_128 { get; set; }
        /// <summary>
        /// 标本编号
        /// </summary>
        public string WS01_00_003_01 { get; set; }
        /// <summary>
        /// 标本状态
        /// </summary>
        public string WS04_50_135_01 { get; set; }
        /// <summary>
        /// 标本部位
        /// </summary>
        public string WS04_30_904_01 { get; set; }
        /// <summary>
        /// 标本采样日期时间
        /// </summary>
        public string WS04_50_137_01 { get; set; }
        /// <summary>
        /// 采样人姓名
        /// </summary>
        public string WS02_01_039_061 { get; set; }
        /// <summary>
        /// 送检人姓名
        /// </summary>
        public string WS02_01_039_055 { get; set; }
        /// <summary>
        /// 送检科室代码
        /// </summary>
        public string WS08_10_025_05 { get; set; }
        /// <summary>
        /// 送检科室名称
        /// </summary>
        public string CT08_10_025_05 { get; set; }
        /// <summary>
        /// 院内送检科室代码
        /// </summary>
        public string WS99_99_902_14 { get; set; }
        /// <summary>
        /// 院内送检科室名称
        /// </summary>
        public string CT99_99_902_14 { get; set; }

        /// <summary>
        /// 送检机构代码
        /// </summary>
        public string WS08_10_052_05 { get; set; } = "47033249933018311H1191";

        /// <summary>
        /// 送检机构名称
        /// </summary>
        public string CT08_10_052_05 { get; set; } = "富阳区第三人民医院";
        /// <summary>
        /// 接收标本日期时间
        /// </summary>
        public string WS04_50_141_01 { get; set; }
        /// <summary>
        /// 核收人姓名
        /// </summary>
        public string WS02_01_039_056 { get; set; }

        /// <summary>
        /// 本次检验是否做了药敏检验的标识（0否【未做】；1是【做】）
        /// </summary>
        public string WS04_50_901_01 { get; set; } = "0";
        /// <summary>
        /// 检测结果描述
        /// </summary>
        public string WS04_50_908_01 { get; set; }
        /// <summary>
        /// 对下达医嘱的补充说明和注意事项提示
        /// </summary>
        public string WS06_00_179_01 { get; set; }
        /// <summary>
        /// 检验技师姓名
        /// </summary>
        public string WS02_01_039_065 { get; set; }
        /// <summary>
        /// 检验医生姓名
        /// </summary>
        public string WS02_01_039_173 { get; set; }
        /// <summary>
        /// 检验日期时间-1、符合【yyyyMMddHHmmss】的格式
        /// </summary>
        public string WS06_00_925_01 { get; set; }
        /// <summary>
        /// 报告医师姓名
        /// </summary>
        public string WS02_01_039_049 { get; set; }
        /// <summary>
        /// 报告医生身份证号
        /// </summary>
        public string WS99_99_906_01 { get; set; }
        /// <summary>
        /// 审核医生身份证号
        /// </summary>
        public string WS99_99_030_04 { get; set; }
        /// <summary>
        /// 审核人姓名
        /// </summary>
        public string WS02_01_039_057 { get; set; }
        /// <summary>
        /// 审核日期时间-1、符合【yyyyMMddHHmmss】的格式
        /// </summary>
        public string WS06_00_927_01 { get; set; }
        /// <summary>
        /// 报告日期时间-1、符合【yyyyMMddHHmmss】的格式
        /// </summary>
        public string WS06_00_926_01 { get; set; }

        /// <summary>
        /// 报告科室代码-1、在【CT08.00.002科室代码】值域范围内，且与【报告科室名称】匹配
        /// </summary>
        public string WS08_10_025_03 { get; set; } = "A30";

        /// <summary>
        /// 报告科室名称
        /// </summary>
        public string CT08_10_025_03 { get; set; } = "医学检验科";

        /// <summary>
        /// 院内报告科室代码
        /// </summary>
        public string WS99_99_902_98 { get; set; } = "301";

        /// <summary>
        /// 院内报告科室名称
        /// </summary>
        public string CT99_99_902_98 { get; set; } = "检验科";

        /// <summary>
        /// 报告机构代码-1、在【CT99.00.001机构代码（本地化）】值域范围内，且与【报告机构名称】匹配
        /// </summary>
        public string WS08_10_052_03 { get; set; } = "47033249933018311H1191";

        /// <summary>
        /// 报告机构名称
        /// </summary>
        public string CT08_10_052_03 { get; set; } = "富阳区第三人民医院";
        /// <summary>
        /// 必填项：N
        /// 检验技师身份证号检验技师身份证号
        /// </summary>
        public string WS99_99_030_10 { get; set; }
        /// <summary>
        /// 必填项：N
        /// 联系电话联系电话
        /// </summary>
        public string WS02_01_010_22 { get; set; }
        /// <summary>
        /// 必填项：Y
        /// 检验目的检验目的
        /// </summary>
        public string WS99_99_034_69 { get; set; }
        /// <summary>
        /// 必填项：Y
        /// 检验目的编码检验目的编码
        /// </summary>
        public string WS99_99_999_24 { get; set; }
        /// <summary>
        /// 必填项：Y
        /// 申请日期时间申请日期时间
        /// </summary>
        public string WS06_00_917_01 { get; set; }
        /// <summary>
        /// 必填项：N
        /// 申请医生身份证号申请医生身份证号
        /// </summary>
        public string WS99_99_030_03 { get; set; }
        /// <summary>
        /// 必填项：Y
        /// 申请医生姓名申请医生姓名
        /// </summary>
        public string WS02_01_039_177 { get; set; }
        /// <summary>
        /// 必填项：Y
        /// 送检日期时间送检日期时间
        /// </summary>
        public string WS06_00_917_03 { get; set; }
        /// <summary>
        /// 必填项：N
        /// 送检医生身份证号送检医生身份证号
        /// </summary>
        public string WS99_99_030_32 { get; set; }
        /// <summary>
        /// 必填项：N
        /// 采样医生身份证号采样医生身份证号
        /// </summary>
        public string WS99_99_030_33 { get; set; }
        /// <summary>
        /// 必填项：N
        /// 接收人身份证号接收人身份证号
        /// </summary>
        public string WS99_99_030_34 { get; set; }
        /// <summary>
        /// 必填项：N
        /// 检验医生身份证号检验医生身份证号
        /// </summary>
        public string WS99_99_030_35 { get; set; }
        /// <summary>
        /// 必填项：N
        /// 报告单查看地址报告单查看地址
        /// </summary>
        public string WS99_99_999_25 { get; set; }
        /// <summary>
        /// 必填项：Y
        /// 诊断信息诊断信息
        /// </summary>
        public string WS99_99_902_685 { get; set; }
        /// <summary>
        /// 必填项：N
        /// 检验互认编码检验互认编码,多个以逗号隔开在【CT99.99.397检验互认编码】值域范围内
        /// </summary>
        public string WS99_99_999_17 { get; set; }
        /// <summary>
        /// 必填项：Y
        /// 是否互认标志是否互认标志在【CT99.99.396是否互认标志】值域范围内
        /// </summary>
        public string WS99_99_999_18 { get; set; }
        /// <summary>
        /// 必填项：N
        /// 作废标识作废标识1、在【CT09.00.001布尔代码】值域范围内
        /// </summary>
        public string WS06_00_906_01 { get; set; }
        /// <summary>
        /// 必填项：N
        /// CA签名值最后一名签名医生（护士）的CA医生签名
        /// </summary>
        public string WS99_99_010_48 { get; set; }


    }


}
