//<auto-generated>
using System;
using System.ComponentModel;
using System.Xml.Serialization;

namespace YYhUpload.Model
{
    //class YYHBatchNumberIn

    // 注意: 生成的代码可能至少需要 .NET Framework 4.5 或 .NET Core/Standard 2.0。
    /// <remarks/>
    [Serializable()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(IsNullable = false,ElementName = "messages")]
    public  class YyhBatchNumber
    {
        /// <remarks/>
        public int heartbeat { get; set; } = 0;

        /// <remarks/>
        public BatchNumberSwitchset switchset { get; set; }

        /// <remarks/>
        public BatchNumberBusiness business { get; set; }

        /// <remarks/>
        public string extendset { get; set; } = "";
    }

    /// <remarks/>
    [Serializable()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public  class BatchNumberSwitchset
    {
        /// <remarks/>
        public BatchNumberSwitchsetAuthority authority { get; set; }

        /// <remarks/>
        public BatchNumberSwitchsetVisitor visitor { get; set; }

        /// <remarks/>
        public BatchNumberSwitchsetServiceinf serviceinf { get; set; }

        /// <remarks/>
        public BatchNumberSwitchsetProvider provider { get; set; }

        /// <remarks/>
        public string route { get; set; } = "";

        /// <remarks/>
        public string process { get; set; } = "";
    }

    /// <remarks/>
    [Serializable()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class BatchNumberSwitchsetAuthority
    {
        /// <remarks/>
        public string authoritytype { get; set; } = "";

        /// <remarks/>
        public string username { get; set; } = "";

        /// <remarks/>
        public string userpwd { get; set; } = "";

        /// <remarks/>
        public string license { get; set; } = "";
    }

    /// <remarks/>
    [Serializable()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class BatchNumberSwitchsetVisitor
    {
        /// <remarks/>
        public string sourceorgan { get; set; } = "3301110000000000000000";

        /// <remarks/>
        public string sourcedomain { get; set; } = "3301000029";
    }

    /// <remarks/>
    [Serializable()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class BatchNumberSwitchsetServiceinf
    {
        /// <remarks/>
        public string servicecode { get; set; } = "XBSJCJCJL:PCRWHHQL";
    }

    /// <remarks/>
    [Serializable()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class BatchNumberSwitchsetProvider
    {
        /// <remarks/>
        public string targetorgan { get; set; } = "";

        /// <remarks/>
        public string targetdomain { get; set; } = "";
    }

    /// <remarks/>
    [Serializable()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class BatchNumberBusiness
    {
        /// <remarks/>
        public string standardcode { get; set; } = "";

        /// <remarks/>
        public BatchNumberRequestSet requestset { get; set; }

        /// <remarks/>
        public string datacompress { get; set; } = "";

        /// <remarks/>
        public string daqtaskid { get; set; } = "";

        /// <remarks/>
        public BatchNumberBusinessData businessdata { get; set; }
    }

    /// <remarks/>
    [Serializable()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class BatchNumberRequestSet
    {
        /// <remarks/>
        public BatchNumberReqcondition BatchNumberReqcondition { get; set; }

        /// <remarks/>
        public string reqpaging { get; set; } = "";

        /// <remarks/>
        public string reqpageindex { get; set; } = "";

        /// <remarks/>
        public string reqpageset { get; set; } = "";
    }

    /// <remarks/>
    [Serializable()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class BatchNumberReqcondition
    {
        /// <remarks/>
        public string condition { get; set; } = "";
    }

    /// <remarks/>
    [Serializable()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class BatchNumberBusinessData
    {
        /// <remarks/>
        public string declaretype { get; set; } = "0";

        /// <remarks/>
        public string collecttype { get; set; } = "0";

        /// <remarks/>
        public TotalDeclare totaldeclare { get; set; }
    }

    /// <remarks/>
    [Serializable()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class TotalDeclare
    {
        /// <summary>
        /// 交换标准编码
        /// </summary>
        public string colrescode { get; set; }

        /// <summary>
        /// 上传的任务次数
        /// </summary>
        public int tasknum { get; set; }

        /// <summary>
        /// 上传数据的开始时间
        /// </summary>
        public string begindatetime { get; set; }

        /// <summary>
        /// 上传数据的结束时间
        /// </summary>
        public string enddatetime { get; set; }

        /// <remarks/>
        public Tdeclare tdeclare { get; set; }
    }

    /// <remarks/>
    [Serializable()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class Tdeclare
    {
        /// <summary>
        /// 数据集编码
        /// </summary>
        public string setcode { get; set; }

        /// <summary>
        /// 上传数据数量（条数）
        /// </summary>
        public int datanum { get; set; }
    }
}
