//<auto-generated>
namespace YYhUpload.Model
{
    public class YYhBase
    {
        public string SERIALNUM_ID { get; set; } = "";
        public string TASK_ID { get; set; } = "";
        public string BATCH_NUM { get; set; } = "";
        public string LOCAL_ID { get; set; } = "";
        public string BUSINESS_ID { get; set; } = "";
        public string BASIC_ACTIVE_ID { get; set; } = "";
        public string DATAGENERATE_DATE { get; set; } = "";
        public string DOMAIN_CODE { get; set; } = "";
        public string ORGANIZATION_CODE { get; set; } = "";
        public string CREATE_DATE { get; set; } = "";
        public string UPDATE_DATE { get; set; } = "";
        public string ARCHIVE_DATE { get; set; } = "";
        public string RECORD_IDEN { get; set; } = "";

    }
}
