//<auto-generated>
using System;
using System.ComponentModel;
using System.Xml.Serialization;

namespace YYhUpload.Model
{
 

        // 注意: 生成的代码可能至少需要 .NET Framework 4.5 或 .NET Core/Standard 2.0。
        /// <remarks/>
        [Serializable()]
        [DesignerCategory("code")]
        [XmlType(AnonymousType = true)]
        [XmlRoot(IsNullable = false,ElementName = "messages",Namespace ="http://www.neusoft.com/hit/rhin")]
        public class YYhBaseReturn
        {
            /// <remarks/>
            public BaseReturnSwitchset switchset { get; set; }

            /// <remarks/>
            public BaseReturnBusiness business { get; set; }

            /// <remarks/>
            public string extendset { get; set; }
        }

        /// <remarks/>
        [Serializable()]
        [DesignerCategory("code")]
        [XmlType(AnonymousType = true)]
        public class BaseReturnSwitchset
    {
            /// <remarks/>
            public BaseReturnSwitchsetVisitor visitor { get; set; }

            /// <remarks/>
            public BaseReturnSwitchsetServiceinf serviceinf { get; set; }

            /// <remarks/>
            public BaseReturnSwitchsetProvider provider { get; set; }

            /// <remarks/>
            public string route { get; set; }

            /// <remarks/>
            public string process { get; set; }

            /// <remarks/>
            public BaseReturnSwitchsetSwitchmessage switchmessage { get; set; }
        }

        /// <remarks/>
        [Serializable()]
        [DesignerCategory("code")]
        [XmlType(AnonymousType = true)]
        public class BaseReturnSwitchsetVisitor
        {
            public string sourceorgan { get; set; }

            /// <remarks/>
            public string sourcedomain { get; set; }
        }

        /// <remarks/>
        [Serializable()]
        [DesignerCategory("code")]
        [XmlType(AnonymousType = true)]
        public class BaseReturnSwitchsetServiceinf
        {
            /// <remarks/>
            public string servicecode { get; set; }
        }

        /// <remarks/>
        [Serializable()]
        [DesignerCategory("code")]
        [XmlType(AnonymousType = true)]
        public class BaseReturnSwitchsetProvider
        {
            /// <remarks/>
            public string targetorgan { get; set; }

            /// <remarks/>
            public string targetdomain { get; set; }
        }

        /// <remarks/>
        [Serializable()]
        [DesignerCategory("code")]
        [XmlType(AnonymousType = true)]
        public class BaseReturnSwitchsetSwitchmessage
        {
            /// <remarks/>
            public string messagecode { get; set; }

            /// <remarks/>
            public string messagetext { get; set; }
        }

        /// <remarks/>
        [Serializable()]
        [DesignerCategory("code")]
        [XmlType(AnonymousType = true)]
        public class BaseReturnBusiness
    {
            /// <remarks/>
            public string standardcode { get; set; }

            /// <remarks/>
            public BaseReturnBusinessReturnmessage returnmessage { get; set; }

            /// <remarks/>
            public BaseReturnBusinessReturnset returnset { get; set; }

            /// <remarks/>
            public byte datacompress { get; set; }

            /// <remarks/>
            public BaseReturnBusinessBusinessdata businessdata { get; set; }
        }

        /// <remarks/>
        [Serializable()]
        [DesignerCategory("code")]
        [XmlType(AnonymousType = true)]
        public class BaseReturnBusinessReturnmessage
        {
            /// <remarks/>
            public int retcode { get; set; }

            /// <remarks/>
            public string rettext { get; set; }
        }

        /// <remarks/>
        [Serializable()]
        [DesignerCategory("code")]
        [XmlType(AnonymousType = true)]
        public class BaseReturnBusinessReturnset
        {
            /// <remarks/>
            public int rettotal { get; set; }

            /// <remarks/>
            public int retpaging { get; set; }

            /// <remarks/>
            public int retpageindex { get; set; }

            /// <remarks/>
            public int retpageset { get; set; }
        }

        /// <remarks/>
        [Serializable()]
        [DesignerCategory("code")]
        [XmlType(AnonymousType = true)]
        public class BaseReturnBusinessBusinessdata
        {
            /// <remarks/>
            public string taskid { get; set; }
        }

}
