//<auto-generated>
using System;
using System.ComponentModel;
using System.Xml.Serialization;

namespace YYhUpload.Model
{
    //class YYhSingleDeclare

    // 注意: 生成的代码可能至少需要 .NET Framework 4.5 或 .NET Core/Standard 2.0。
    /// <remarks/>
    [Serializable()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(IsNullable = false, ElementName = "messages")]
    public class YYhSingleDeclare
    {

        /// <remarks/>
        public int heartbeat { get; set; } = 0;

        /// <remarks/>
        public SingleDeclareSwitchset switchset { get; set; }

        /// <remarks/>
        public SingleDeclareBusiness business { get; set; }

        /// <remarks/>
        public string extendset { get; set; }
    }

    /// <remarks/>
    [Serializable()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class SingleDeclareSwitchset
    {

        /// <remarks/>
        public SingleDeclareSwitchsetAuthority authority { get; set; }

        /// <remarks/>
        public SingleDeclareSwitchsetVisitor visitor { get; set; }

        /// <remarks/>
        public SingleDeclareSwitchsetServiceinf serviceinf { get; set; }

        /// <remarks/>
        public SingleDeclareSwitchsetProvider provider { get; set; }

        /// <remarks/>
        public string route { get; set; } = "";

        /// <remarks/>
        public string process { get; set; } = "";
    }

    /// <remarks/>
    [Serializable()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class SingleDeclareSwitchsetAuthority
    {

        /// <remarks/>
        public string authoritytype { get; set; } = "";

        /// <remarks/>
        public string username { get; set; } = "";

        /// <remarks/>
        public string userpwd { get; set; } = "";

        /// <remarks/>
        public object license { get; set; } = "";
    }

    /// <remarks/>
    [Serializable()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class SingleDeclareSwitchsetVisitor
    {

        /// <remarks/>
        public string sourceorgan { get; set; } = "3301110000000000000000";

        /// <remarks/>
        public string sourcedomain { get; set; } = "3301000029";
    }

    /// <remarks/>
    [Serializable()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class SingleDeclareSwitchsetServiceinf
    {

        /// <remarks/>
        public string servicecode { get; set; } = "XBSJCJCJL:HQDCRWHL";
    }

    /// <remarks/>
    [Serializable()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class SingleDeclareSwitchsetProvider
    {

        /// <remarks/>
        public string targetorgan { get; set; } = "";

        /// <remarks/>
        public string targetdomain { get; set; } = "";
    }

    /// <remarks/>
    [Serializable()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class SingleDeclareBusiness
    {

        /// <remarks/>
        public string standardcode { get; set; }

        /// <remarks/>
        public SingleDeclareBusinessRequestset requestset { get; set; }

        /// <remarks/>
        public string datacompress { get; set; } = "";

        /// <remarks/>
        public string daqtaskid { get; set; } = $"{DateTime.Now:yyyyMMddHHmmssfff}";

        /// <remarks/>
        public SingleDeclareBusinessData businessdata { get; set; }
    }

    /// <remarks/>
    [Serializable()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class SingleDeclareBusinessRequestset
    {

        /// <remarks/>
        public SingleDeclareReqcondition reqcondition { get; set; }

        /// <remarks/>
        public string reqpaging { get; set; } = "";

        /// <remarks/>
        public string reqpageindex { get; set; } = "";

        /// <remarks/>
        public string reqpageset { get; set; } = "";
    }

    /// <remarks/>
    [Serializable()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class SingleDeclareReqcondition
    {

        /// <remarks/>
        public string condition { get; set; } = "";
    }

    /// <remarks/>
    [Serializable()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class SingleDeclareBusinessData
    {

        /// <remarks/>
        public string declaretype { get; set; } = "0";

        /// <remarks/>
        public SingleDeclare singledeclare { get; set; }
    }

    /// <remarks/>
    [Serializable()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class SingleDeclare
    {

        /// <remarks/>
        public string totaltaskid { get; set; }

        /// <remarks/>
        public string colrescode { get; set; }

        /// <remarks/>
        public int sn { get; set; }

        /// <remarks/>
        public SDeclare declare { get; set; }
    }

    /// <remarks/>
    [Serializable()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class SDeclare
    {

        /// <summary>
        /// 数据交换代码
        /// </summary>
        public string setcode { get; set; }

        /// <summary>
        /// 数据条数
        /// </summary>
        public int datanum { get; set; }
    }


}
