//<auto-generated>
namespace YYhUpload.Model
{
    /// <summary>
    /// 住院检验申请单
    /// </summary>
    public class Zy_Jysqd : YYhBase
    {
        /// <summary>
        ///本人姓名
        ///本人在公安管理部门正式登记注册的姓氏和名称
        /// </summary>
        public string WS02_01_039_001 { get; set; }
        /// <summary>
        ///性别代码
        ///本人生理性别的代码
        /// 1、在【GB/T2261.1人的性别代码】值域范围内，且与【性别名称】匹配
        /// </summary>
        public string WS02_01_040_01 { get; set; }
        /// <summary>
        ///性别名称
        ///本人生理性别的名称
        /// </summary>
        public string CT02_01_040_01 { get; set; }
        /// <summary>
        ///身份证件类别代码
        ///本人身份证件类别的代码
        /// 1、在【CV02.01.101身份证件类别代码表】值域范围内，且与【身份证件类别名称】匹配
        /// </summary>
        public string WS02_01_031_01 { get; set; }
        /// <summary>
        ///身份证件类别名称
        ///本人身份证件类别的名称
        /// </summary>
        public string CT02_01_031_01 { get; set; }
        /// <summary>
        ///Y
        ///身份证件号码
        ///身份证件上唯一的法定标识符
        /// </summary>
        public string WS02_01_030_01 { get; set; }
        /// <summary>
        ///年龄(岁)
        ///患者年龄满1周岁的实足年龄，为患者出生后按照日历计算的历法年龄，以实足年龄的相应整数填写
        /// 1、类型为数值
        /// </summary>
        public string WS02_01_026_01 { get; set; }
        /// <summary>
        ///年龄(月)
        ///年龄不足1周岁的实足年龄的月龄，以分数形式表示：分数的整数部分代表实足月龄，分数部分分母为30，分子为不足1个月的天数（例如12/30）
        /// </summary>
        public string WS02_01_032_02 { get; set; }
        /// <summary>
        ///年龄（日）
        ///年龄不足1周月的实足年龄的日龄
        /// </summary>
        public string WS99_99_026_01 { get; set; }
        /// <summary>
        ///年龄（小时）
        ///年龄不足1周日的实足年龄的时龄
        /// </summary>
        public string WS99_99_026_02 { get; set; }
        /// <summary>
        ///卡号
        ///根据不同卡类型，患者提供的卡号
        /// </summary>
        public string WS99_99_903_40 { get; set; }
        /// <summary>
        ///卡类型代码
        ///患者提供的有效卡的类型代码
        /// </summary>
        public string WS99_99_902_07 { get; set; }
        /// <summary>
        ///卡类型名称
        ///患者提供的有效卡的卡类型名称
        /// </summary>
        public string CT99_99_902_07 { get; set; }
        /// <summary>
        ///患者类型代码
        ///患者就诊类型的分类代码
        /// 1、在【CV09.00.404患者类型代码】值域范围内，且与【患者类型名称】匹配
        /// </summary>
        public string WS02_01_060_01 { get; set; }
        /// <summary>
        ///患者类型名称
        ///患者就诊类型的分类名称
        /// </summary>
        public string CT02_01_060_01 { get; set; }
        /// <summary>
        ///出生日期
        ///卫生服务对象出生当日的公元纪年日期
        /// 1、符合【yyyyMMdd】的格式
        /// </summary>
        public string WS02_01_005_01_01 { get; set; }
        /// <summary>
        ///联系人电话号码
        ///联系人的电话号码，包括国际、国内区号和分机号
        /// </summary>
        public string WS02_01_010_02 { get; set; }
        /// <summary>
        ///Y
        ///电子申请单编号
        ///按照某一特定编码规则赋予电子申请单的顺序号
        /// </summary>
        public string WS01_00_008_03 { get; set; }
        /// <summary>
        ///申请单名称
        ///用于描述在一张申请单上检查、检验项目的具体名称（例如血常规、肝功10项）
        /// </summary>
        public string WS01_00_906_01 { get; set; }
        /// <summary>
        ///报告单编号
        ///按照某一特定编码规则赋予报告单的顺序号
        /// </summary>
        public string WS01_00_018_01 { get; set; }
        /// <summary>
        ///本人电话号码
        ///本人联系电话的号码，包括国际、国内区号和分机号
        /// </summary>
        public string WS02_01_010_01 { get; set; }
        /// <summary>
        ///Y
        ///住院号
        ///按照某一特定编码规则赋予住院就诊对象的顺序号
        /// </summary>
        public string WS01_00_014_01 { get; set; }
        /// <summary>
        ///病区名称
        ///患者当前所在病区的名称
        /// </summary>
        public string WS08_10_054_01 { get; set; }
        /// <summary>
        ///病房号
        ///患者住院期间，所住病房对应的编号
        /// </summary>
        public string WS01_00_019_01 { get; set; }
        /// <summary>
        ///病床号
        ///患者住院期间，所住床位对应的编号
        /// </summary>
        public string WS01_00_026_01 { get; set; }
        /// <summary>
        ///作废标识
        ///标识该医嘱（处方）、申请单等是否作废（0否【未作废】；1 是【作废】）
        /// 1、在【CT09.00.001布尔代码】值域范围内
        /// </summary>
        public string WS06_00_901_01 { get; set; }
        /// <summary>
        ///项目序号
        ///用于描述本条记录的排列顺序号码
        /// </summary>
        public string WS01_00_907_01 { get; set; }
        /// <summary>
        ///检查/检验项目编码
        ///受检者检查/检验项目在特定编码体系中的编码,如LOINC 的代码值
        /// </summary>
        public string WS04_30_019_01 { get; set; }
        /// <summary>
        ///检查/检验项目名称
        ///检查报告项目的名称
        /// </summary>
        public string WS04_30_020_01 { get; set; }
        /// <summary>
        ///申请项目代码
        ///申请检查项目在机构诊疗项目目录中的编码
        /// </summary>
        public string WS02_10_916_01 { get; set; }
        /// <summary>
        ///申请项目名称
        ///申请检查项目的名称
        /// </summary>
        public string WS02_10_916_02 { get; set; }
        /// <summary>
        ///检验类别代码
        ///受检者检验项目所属的类别的代码
        /// 1、在【CT04.10.013检验类别代码】值域范围内，且与【检验类别名称】匹配
        /// </summary>
        public string WS04_30_018_02 { get; set; }
        /// <summary>
        ///检验类别名称
        ///受检者检验项目所属的类别的名称
        /// </summary>
        public string CT04_30_018_02 { get; set; }
        /// <summary>
        ///院内检验类别代码
        ///院内检验类别代码
        /// </summary>
        public string WS99_99_902_94 { get; set; }
        /// <summary>
        ///Y
        ///申请日期时间
        ///提交申请时的公元纪年日期和时间的完整描述
        /// 1、符合【yyyyMMddHHmmss】的格式
        /// </summary>
        public string WS06_00_917_01 { get; set; }
        /// <summary>
        ///申请人姓名
        ///开立检验或检查申请人签署的在公安户籍管理部门正式登记注册的姓氏和名称
        /// </summary>
        public string WS02_01_039_097 { get; set; }
        /// <summary>
        ///申请医生身份证号
        ///申请医生身份证件上唯一的法定标识符
        /// </summary>
        public string WS99_99_030_03 { get; set; }
        /// <summary>
        ///申请科室代码
        ///申请检查、检验的科室代码
        /// 1、在【CT08.00.002科室代码】值域范围内，且与【申请科室名称】匹配
        /// </summary>
        public string WS08_10_025_02 { get; set; }
        /// <summary>
        ///院内申请科室代码
        ///院内申请科室代码
        /// </summary>
        public string WS99_99_902_95 { get; set; }
        /// <summary>
        ///申请科室名称
        ///申请检查、检验的科室名称
        /// </summary>
        public string CT08_10_025_02 { get; set; }
        /// <summary>
        ///Y
        ///申请机构代码
        ///申请作检查、检验项目的医疗机构的代码
        /// 1、在【CT99.00.001机构代码（本地化）】值域范围内，且与【申请机构名称】匹配
        /// </summary>
        public string WS08_10_052_02 { get; set; }
        /// <summary>
        ///Y
        ///申请机构名称
        ///申请作检查、检验项目的医疗机构的名称
        /// </summary>
        public string CT08_10_052_02 { get; set; }
        /// <summary>
        ///疾病诊断编码
        ///患者所患的疾病诊断特定编码体系中的编码
        /// 1、在【ICD-10国际疾病分类标准编码】值域范围内，且与【疾病诊断名称】匹配
        /// </summary>
        public string WS05_01_024_01 { get; set; }
        /// <summary>
        ///疾病诊断名称
        ///患者所患疾病的西医诊断名称
        /// </summary>
        public string CT05_01_024_01 { get; set; }
        /// <summary>
        ///被申请机构代码
        ///被申请作检查、检验项目的医疗机构的代码
        /// 1、在【CT99.00.001机构代码（本地化）】值域范围内，且与【被申请机构名称】匹配
        /// </summary>
        public string WS08_10_052_22 { get; set; }
        /// <summary>
        ///被申请机构名称
        ///被申请作检查、检验项目的医疗机构的名称
        /// </summary>
        public string CT08_10_052_22 { get; set; }
        /// <summary>
        ///院内申请科室名称
        ///院内申请科室名称
        /// </summary>
        public string CT99_99_902_95 { get; set; }
        /// <summary>
        ///CA签名值
        ///最后一名签名医生（护士）的CA医生签名
        /// </summary>
        public string WS99_99_010_48 { get; set; }
    }
}
