//<auto-generated>
namespace YYhUpload.Model
{
    /// <summary>
    /// 住院检验报告
    /// </summary>
    public class Zy_Jybg:YYhBase
    {
        /// <summary>
        ///本人姓名
        ///本人在公安管理部门正式登记注册的姓氏和名称
        /// </summary>
        public string WS02_01_039_001 { get; set; }
        /// <summary>
        ///性别代码
        ///本人生理性别的代码
        /// 1、在【GB/T2261.1人的性别代码】值域范围内，且与【性别名称】匹配
        /// </summary>
        public string WS02_01_040_01 { get; set; }
        /// <summary>
        ///性别名称
        ///本人生理性别的名称
        /// </summary>
        public string CT02_01_040_01 { get; set; }
        /// <summary>
        ///年龄(岁)
        ///患者年龄满1周岁的实足年龄，为患者出生后按照日历计算的历法年龄，以实足年龄的相应整数填写
        /// 1、类型为数值
        /// </summary>
        public string WS02_01_026_01 { get; set; }
        /// <summary>
        ///年龄(月)
        ///年龄不足1周岁的实足年龄的月龄，以分数形式表示：分数的整数部分代表实足月龄，分数部分分母为30，分子为不足1个月的天数（例如12/30）
        /// </summary>
        public string WS02_01_032_02 { get; set; }
        /// <summary>
        ///年龄（日）
        ///年龄不足1周月的实足年龄的日龄
        /// </summary>
        public string WS99_99_026_01 { get; set; }
        /// <summary>
        ///年龄（小时）
        ///年龄不足1周日的实足年龄的时龄
        /// </summary>
        public string WS99_99_026_02 { get; set; }
        /// <summary>
        ///卡号
        ///根据不同卡类型，患者提供的卡号
        /// </summary>
        public string WS99_99_903_40 { get; set; }
        /// <summary>
        ///卡类型代码
        ///患者提供的有效卡的类型代码
        /// </summary>
        public string WS99_99_902_07 { get; set; }
        /// <summary>
        ///卡类型名称
        ///患者提供的有效卡的卡类型名称
        /// </summary>
        public string CT99_99_902_07 { get; set; }

        /// <summary>
        /// 患者ID	患者在医院内部的唯一编号
        /// </summary>
        public string WS99_99_999_16 { get; set; }
        /// <summary>
        ///患者类型代码
        ///患者就诊类型的分类代码
        /// 1、在【CV09.00.404患者类型代码】值域范围内，且与【患者类型名称】匹配
        /// </summary>
        public string WS02_01_060_01 { get; set; }
        /// <summary>
        ///患者类型名称
        ///患者就诊类型的分类名称
        /// </summary>
        public string CT02_01_060_01 { get; set; }
        /// <summary>
        ///出生日期
        ///卫生服务对象出生当日的公元纪年日期
        /// 1、符合【yyyyMMdd】的格式
        /// </summary>
        public string WS02_01_005_01_01 { get; set; }
        /// <summary>
        ///身份证件类别代码
        ///本人身份证件类别的代码
        /// 1、在【CV02.01.101身份证件类别代码表】值域范围内，且与【身份证件类别名称】匹配
        /// </summary>
        public string WS02_01_031_01 { get; set; }
        /// <summary>
        ///身份证件类别名称
        ///本人身份证件类别的名称
        /// </summary>
        public string CT02_01_031_01 { get; set; }
        /// <summary>
        ///Y
        ///身份证件号码
        ///身份证件上唯一的法定标识符
        /// </summary>
        public string WS02_01_030_01 { get; set; }
        /// <summary>
        ///本人电话号码
        ///本人联系电话的号码，包括国际、国内区号和分机号
        /// </summary>
        public string WS02_01_010_01 { get; set; }
        /// <summary>
        ///Y
        ///住院号
        ///按照某一特定编码规则赋予住院就诊对象的顺序号
        /// </summary>
        public string WS01_00_014_01 { get; set; }
        /// <summary>
        ///病区名称
        ///患者当前所在病区的名称
        /// </summary>
        public string WS08_10_054_01 { get; set; }
        /// <summary>
        ///病房号
        ///患者住院期间，所住病房对应的编号
        /// </summary>
        public string WS01_00_019_01 { get; set; }
        /// <summary>
        ///病床号
        ///患者住院期间，所住床位对应的编号
        /// </summary>
        public string WS01_00_026_01 { get; set; }
        /// <summary>
        ///不填
        ///电子申请单编号
        ///按照某一特定编码规则赋予电子申请单的顺序号
        /// </summary>
        public string WS01_00_008_03 { get; set; }
        /// <summary>
        ///Y
        ///报告单编号
        ///按照某一特定编码规则赋予报告单的顺序号
        /// </summary>
        public string WS01_00_018_01 { get; set; }
        /// <summary>
        ///报告单名称
        ///报告单名称
        /// </summary>
        public string WS01_00_900_02 { get; set; }
        /// <summary>
        ///报告单类别代码
        ///报告单出具时的类别代码描述（1临时报告；2最终报告）
        /// 1、在【CT01.00.003报告单类别代码】值域范围内
        /// </summary>
        public string WS01_00_900_01 { get; set; }
        /// <summary>
        ///申请项目代码
        ///申请检查项目在机构诊疗项目目录中的编码
        /// </summary>
        public string WS02_10_916_01 { get; set; }
        /// <summary>
        ///申请项目名称
        ///申请检查项目的名称
        /// </summary>
        public string WS02_10_916_02 { get; set; }
        /// <summary>
        ///标本类别代码
        ///对标本类别所属分类的代码
        /// 1、在【CT04.50.008标本类别代码】值域范围内，且与【标本类别名称】匹配
        /// </summary>
        public string WS04_50_134_01 { get; set; }
        /// <summary>
        ///标本类别名称
        ///标本类别所属分类的名称
        /// </summary>
        public string CT04_50_134_01 { get; set; }
        /// <summary>
        ///标本编号
        ///按照某一特定编码规则赋予检查、检验标本的顺序号
        /// </summary>
        public string WS01_00_003_01 { get; set; }
        /// <summary>
        ///标本状态
        ///对受检标本状态的描述
        /// </summary>
        public string WS04_50_135_01 { get; set; }
        /// <summary>
        ///标本部位
        ///病理标本所取患者部位
        /// </summary>
        public string WS04_30_904_01 { get; set; }
        /// <summary>
        ///标本采样日期时间
        ///采集标本时的公元纪年日期和时间的完整描述
        /// 1、符合【yyyyMMddHHmmss】的格式
        /// </summary>
        public string WS04_50_137_01 { get; set; }
        /// <summary>
        ///采样人姓名
        ///采样人员在公安户籍管理部门正式登记注册的姓氏和名称
        /// </summary>
        public string WS02_01_039_061 { get; set; }
        /// <summary>
        ///送检人姓名
        ///送检人在公安户籍管理部门正式登记注册的姓氏和名称
        /// </summary>
        public string WS02_01_039_055 { get; set; }
        /// <summary>
        ///送检科室代码
        ///送检科室代码
        /// 1、在【CT08.00.002科室代码】值域范围内，且与【送检科室名称】匹配
        /// </summary>
        public string WS08_10_025_05 { get; set; }
        /// <summary>
        ///送检科室名称
        ///送检科室名称
        /// </summary>
        public string CT08_10_025_05 { get; set; }


        public string WS99_99_902_14 { get; set; }


        public string CT99_99_902_14 { get; set; }


        /// <summary>
        ///接收标本日期时间
        ///检查科室实际接收标本时的公元纪年日期和时间的完整描述
        /// 1、符合【yyyyMMddHHmmss】的格式
        /// </summary>
        public string WS04_50_141_01 { get; set; }
        /// <summary>
        ///核收人姓名
        ///核收人在户籍管理部门正式登记注册的姓氏和名称
        /// </summary>
        public string WS02_01_039_056 { get; set; }
        /// <summary>
        ///是否做药敏实验
        ///本次检验是否做了药敏检验的标识（0否【未做】；1是【做】）
        /// 1、在【CT09.00.001布尔代码】值域范围内
        /// </summary>
        public string WS04_50_901_01 { get; set; }
        /// <summary>
        ///检测结果
        ///检测结果描述
        /// </summary>
        public string WS04_50_908_01 { get; set; }
        /// <summary>
        ///备注信息
        ///对下达医嘱的补充说明和注意事项提示
        /// </summary>
        public string WS06_00_179_01 { get; set; }
        /// <summary>
        ///检验技师姓名
        ///检验技师签署的在公安户籍管理部门正式登记注册的姓氏和名称
        /// </summary>
        public string WS02_01_039_065 { get; set; }
        /// <summary>
        ///检验医生姓名
        ///检验医生姓名
        /// </summary>
        public string WS02_01_039_173 { get; set; }
        /// <summary>
        ///Y
        ///检验日期时间
        ///检验当日的公元纪年日期和时间
        /// 1、符合【yyyyMMddHHmmss】的格式
        /// </summary>
        public string WS06_00_925_01 { get; set; }
        /// <summary>
        ///报告医师姓名
        ///报告医师在公安管理部门正式登记注册的姓氏和名称
        /// </summary>
        public string WS02_01_039_049 { get; set; }
        /// <summary>
        ///报告医生身份证号
        ///报告医生的身份证上唯一的法定标识符
        /// </summary>
        public string WS99_99_906_01 { get; set; }
        /// <summary>
        ///报告日期时间
        ///生成报告的当日的公元纪年日期和时间
        /// 1、符合【yyyyMMddHHmmss】的格式
        /// </summary>
        public string WS06_00_926_01 { get; set; }
        /// <summary>
        ///审核人姓名
        ///审核人签署的在公安户籍管理部门正式登记注册的姓氏和名称
        /// </summary>
        public string WS02_01_039_057 { get; set; }
        /// <summary>
        ///审核医生身份证号
        ///审核医生身份证件上唯一的法定标识符
        /// </summary>
        public string WS99_99_030_04 { get; set; }
        /// <summary>
        ///审核日期时间
        ///审核完成的当日的公元纪年日期和时间
        /// 1、符合【yyyyMMddHHmmss】的格式
        /// </summary>
        public string WS06_00_927_01 { get; set; }
        /// <summary>
        ///报告科室代码
        ///出具检查、检验报告的科室的代码
        /// 1、在【CT08.00.002科室代码】值域范围内，且与【报告科室名称】匹配
        /// </summary>
        public string WS08_10_025_03 { get; set; }
        /// <summary>
        ///报告科室名称
        ///出具检查、检验报告的科室的名称
        /// </summary>
        public string CT08_10_025_03 { get; set; }
        /// <summary>
        ///院内科室代码
        ///医院内部的科室按照一定的编码规则编写的代码
        /// </summary>
        public string WS99_99_902_08 { get; set; }
        /// <summary>
        ///科室代码
        ///患者在医疗机构就诊的科室代码
        /// 1、在【CT08.00.002科室代码】值域范围内，且与【科室名称】匹配
        /// </summary>
        public string WS08_10_025_01 { get; set; }
        /// <summary>
        ///科室名称
        ///患者在医疗机构就诊的科室名称
        /// </summary>
        public string CT08_10_025_01 { get; set; }
        /// <summary>
        ///医疗机构组织机构代码
        ///经《医疗机构执业许可证》登记的，并按照特定编码体系填写的代码
        /// 1、在【CT99.00.001机构代码（本地化）】值域范围内
        /// </summary>
        public string WS08_10_052_01 { get; set; }
        /// <summary>
        ///医疗机构组织机构名称
        ///经《医疗机构执业许可证》登记的，并按照特定编码体系填写的名称
        /// </summary>
        public string CT08_10_052_01 { get; set; }
        /// <summary>
        ///送检机构代码
        ///送检机构代码
        /// 1、在【CT99.00.001机构代码（本地化）】值域范围内，且与【送检机构名称】匹配
        /// </summary>
        public string WS08_10_052_05 { get; set; }
        /// <summary>
        ///送检机构名称
        ///送检机构名称
        /// </summary>
        public string CT08_10_052_05 { get; set; }
        /// <summary>
        ///Y
        ///报告机构代码
        ///出具检查、检验的报告单的医疗机构的代码
        /// 1、在【CT99.00.001机构代码（本地化）】值域范围内，且与【报告机构名称】匹配
        /// </summary>
        public string WS08_10_052_03 { get; set; }
        /// <summary>
        ///Y
        ///报告机构名称
        ///出具检查、检验的报告单的医疗机构的名称
        /// </summary>
        public string CT08_10_052_03 { get; set; }
        /// <summary>
        /// 必填项：N
        /// 联系电话联系电话
        /// </summary>
        public string WS02_01_010_22 { get; set; }
        /// <summary>
        /// 必填项：Y
        /// 检验目的检验目的
        /// </summary>
        public string WS99_99_034_69 { get; set; }
        /// <summary>
        /// 必填项：Y
        /// 检验目的编码检验目的编码
        /// </summary>
        public string WS99_99_999_24 { get; set; }
        /// <summary>
        /// 必填项：Y
        /// 申请日期时间申请日期时间
        /// </summary>
        public string WS06_00_917_01 { get; set; }
        /// <summary>
        /// 必填项：N
        /// 申请医生身份证号申请医生身份证号
        /// </summary>
        public string WS99_99_030_03 { get; set; }
        /// <summary>
        /// 必填项：Y
        /// 申请医生姓名申请医生姓名
        /// </summary>
        public string WS02_01_039_177 { get; set; }
        /// <summary>
        /// 必填项：Y
        /// 送检日期时间送检日期时间
        /// </summary>
        public string WS06_00_917_03 { get; set; }
        /// <summary>
        /// 必填项：N
        /// 送检医生身份证号送检医生身份证号
        /// </summary>
        public string WS99_99_030_32 { get; set; }
        /// <summary>
        /// 必填项：N
        /// 采样医生身份证号采样医生身份证号
        /// </summary>
        public string WS99_99_030_33 { get; set; }
        /// <summary>
        /// 必填项：N
        /// 接收人身份证号接收人身份证号
        /// </summary>
        public string WS99_99_030_34 { get; set; }
        /// <summary>
        /// 必填项：N
        /// 检验医生身份证号检验医生身份证号
        /// </summary>
        public string WS99_99_030_35 { get; set; }
        /// <summary>
        /// 必填项：N
        /// 报告单查看地址报告单查看地址
        /// </summary>
        public string WS99_99_999_25 { get; set; }
        /// <summary>
        /// 必填项：Y
        /// 诊断信息诊断信息
        /// </summary>
        public string WS99_99_902_685 { get; set; }
        /// <summary>
        /// 必填项：N
        /// 检验互认编码检验互认编码,多个以逗号隔开在【CT99.99.397检验互认编码】值域范围内
        /// </summary>
        public string WS99_99_999_17 { get; set; }
        /// <summary>
        /// 必填项：Y
        /// 是否互认标志是否互认标志在【CT99.99.396是否互认标志】值域范围内
        /// </summary>
        public string WS99_99_999_18 { get; set; }
        /// <summary>
        /// 必填项：N
        /// 作废标识作废标识1、在【CT09.00.001布尔代码】值域范围内
        /// </summary>
        public string WS06_00_906_01 { get; set; }

        /// <summary>
        ///CA签名值
        ///最后一名签名医生（护士）的CA医生签名
        /// </summary>
        public string WS99_99_010_48 { get; set; }
    }
}
