//<auto-generated>

namespace YYhUpload.Model
{
    /// <summary>
    /// 住院检验常规报告
    /// </summary>
    public class Zy_Jycgbg : YYhBase
    {
        /// <summary>
        ///本人姓名
        ///本人在公安管理部门正式登记注册的姓氏和名称
        /// </summary>
        public string WS02_01_039_001 { get; set; }
        /// <summary>
        ///性别代码
        ///本人生理性别的代码
        /// 1、在【GB/T2261.1人的性别代码】值域范围内，且与【性别名称】匹配
        /// </summary>
        public string WS02_01_040_01 { get; set; }
        /// <summary>
        ///性别名称
        ///本人生理性别的名称
        /// </summary>
        public string CT02_01_040_01 { get; set; }
        /// <summary>
        ///年龄(岁)
        ///患者年龄满1周岁的实足年龄，为患者出生后按照日历计算的历法年龄，以实足年龄的相应整数填写
        /// 1、类型为数值
        /// </summary>
        public string WS02_01_026_01 { get; set; }
        /// <summary>
        ///年龄(月)
        ///年龄不足1周岁的实足年龄的月龄，以分数形式表示：分数的整数部分代表实足月龄，分数部分分母为30，分子为不足1个月的天数（例如12/30）
        /// </summary>
        public string WS02_01_032_02 { get; set; }
        /// <summary>
        ///出生日期
        ///卫生服务对象出生当日的公元纪年日期
        /// 1、符合【yyyyMMdd】的格式
        /// </summary>
        public string WS02_01_005_01_01 { get; set; }
        /// <summary>
        ///身份证件类别代码
        ///本人身份证件类别的代码
        /// 1、在【CV02.01.101身份证件类别代码表】值域范围内，且与【身份证件类别名称】匹配
        /// </summary>
        public string WS02_01_031_01 { get; set; }
        /// <summary>
        ///身份证件类别名称
        ///本人身份证件类别的名称
        /// </summary>
        public string CT02_01_031_01 { get; set; }
        /// <summary>
        ///Y
        ///身份证件号码
        ///身份证件上唯一的法定标识符
        /// </summary>
        public string WS02_01_030_01 { get; set; }

        /// <summary>
        /// 患者ID	患者在医院内部的唯一编号
        /// </summary>
        public string WS99_99_999_16 { get; set; }
        /// <summary>
        ///门(急)诊号
        ///按照某一特定编码规则赋予门（急）诊就诊对象的顺序号
        /// </summary>
        public string WS01_00_010_01 { get; set; }
        /// <summary>
        ///Y
        ///住院号
        ///按照某一特定编码规则赋予住院就诊对象的顺序号
        /// </summary>
        public string WS01_00_014_01 { get; set; }
        /// <summary>
        ///电子申请单编号
        ///按照某一特定编码规则赋予电子申请单的顺序号
        /// </summary>
        public string WS01_00_008_03 { get; set; }
        /// <summary>
        ///Y
        ///报告单编号
        ///按照某一特定编码规则赋予报告单的顺序号
        /// </summary>
        public string WS01_00_018_01 { get; set; }
        /// <summary>
        ///Y
        ///项目序号
        ///用于描述本条记录的排列顺序号码
        /// </summary>
        public string WS01_00_907_01 { get; set; }
        /// <summary>
        ///检查/检验项目编码
        ///受检者检查/检验项目在特定编码体系中的编码,如LOINC 的代码值
        /// </summary>
        public string WS04_30_019_01 { get; set; }
        /// <summary>
        ///检查/检验项目名称
        ///检查报告项目的名称
        /// </summary>
        public string WS04_30_020_01 { get; set; }
        /// <summary>
        ///申请项目代码
        ///申请检查项目在机构诊疗项目目录中的编码
        /// </summary>
        public string WS02_10_916_01 { get; set; }
        /// <summary>
        ///申请项目名称
        ///申请检查项目的名称
        /// </summary>
        public string WS02_10_916_02 { get; set; }
        /// <summary>
        ///检验结果（数值）
        ///患者检验结果数值
        /// </summary>
        public string WS04_30_009_03 { get; set; }
        /// <summary>
        ///院内检验结果代码
        ///院内检验结果代码
        /// </summary>
        public string WS99_99_902_96 { get; set; }
        /// <summary>
        ///临床意义
        ///对该检验项目在临床上的意义和医生建议的描述
        /// </summary>
        public string WS05_01_904_02 { get; set; }
        /// <summary>
        ///危急值标志
        ///危急值标志
        /// 1、类型为数值1、在【CT05.01.001是否代码】值域范围内
        /// </summary>
        public string WS05_10_926_01 { get; set; }
        /// <summary>
        ///检验结果代码
        ///检验结果代码 （1 正常；2异常）
        /// 1、在【CT04.30.001正异结果代码】值域范围内
        /// </summary>
        public string WS04_30_009_06 { get; set; }
        /// <summary>
        ///仪器名称
        ///检验仪器名称
        /// </summary>
        public string WS04_30_023_05 { get; set; }
        /// <summary>
        ///仪器编码
        ///检验仪器编码
        /// </summary>
        public string WS04_30_023_04 { get; set; }
        /// <summary>
        ///计量单位
        ///受检者定量检查/检验结果测量值的计量单位
        /// </summary>
        public string WS04_30_016_01 { get; set; }
        /// <summary>
        ///检验结果描述
        ///对检验结果的详细描述
        /// </summary>
        public string WS04_50_913_01 { get; set; }
        /// <summary>
        ///参考值
        ///检验结果在合理区间内的参数
        /// </summary>
        public string WS04_50_902_01 { get; set; }
        /// <summary>
        ///异常结果
        ///每一项检验结果的异常信息，如：上下箭头、加减号、H、L 等偏差异常结果的表示符号
        /// </summary>
        public string WS04_10_903_01 { get; set; }
        /// <summary>
        ///检查、检验方法
        ///患者接受医学检查项目所采用的检查方法
        /// </summary>
        public string WS02_10_027_01 { get; set; }
        /// <summary>
        ///医疗机构组织机构代码
        ///经《医疗机构执业许可证》登记的，并按照特定编码体系填写的代码
        /// 1、在【CT99.00.001机构代码（本地化）】值域范围内
        /// </summary>
        public string WS08_10_052_01 { get; set; }
        /// <summary>
        ///医疗机构组织机构名称
        ///经《医疗机构执业许可证》登记的，并按照特定编码体系填写的名称
        /// </summary>
        public string CT08_10_052_01 { get; set; }
        /// <summary>
        ///科室代码
        ///患者在医疗机构就诊的科室代码
        /// 1、在【CT08.00.002科室代码】值域范围内，且与【科室名称】匹配
        /// </summary>
        public string WS08_10_025_01 { get; set; }
        /// <summary>
        ///院内科室代码
        ///医院内部的科室按照一定的编码规则编写的代码
        /// </summary>
        public string WS99_99_902_08 { get; set; }
        /// <summary>
        ///科室名称
        ///患者在医疗机构就诊的科室名称
        /// </summary>
        public string CT08_10_025_01 { get; set; }
        /// <summary>
        ///报告机构代码
        ///出具检查、检验的报告单的医疗机构的代码
        /// 1、在【CT99.00.001机构代码（本地化）】值域范围内，且与【报告机构名称】匹配
        /// </summary>
        public string WS08_10_052_03 { get; set; }
        /// <summary>
        ///报告机构名称
        ///出具检查、检验的报告单的医疗机构的名称
        /// </summary>
        public string CT08_10_052_03 { get; set; }
        /// <summary>
        ///Y
        ///报告日期时间
        ///生成报告的当日的公元纪年日期和时间
        /// 1、符合【yyyyMMddHHmmss】的格式
        /// </summary>
        public string WS06_00_926_01 { get; set; }
        /// <summary>
        /// 检验互认编码
        /// </summary>
        public string WS99_99_999_17 { get; set; }
        /// <summary>
        /// 结果正常标志
        /// </summary>
        public string WS99_99_999_19 { get; set; }

        /// <summary>
        /// 检验日期时间
        /// </summary>
        public string WS06_00_925_01 { get; set; }
        /// <summary>
        ///CA签名值
        ///最后一名签名医生（护士）的CA医生签名
        /// 1、住院检验报告有CA 签名可不填
        /// </summary>
        public string WS99_99_010_48 { get; set; }
    }
}
