//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YYhUpload.YYhUploadService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.entrance.si.neusoft.com/")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice.entrance.si.neusoft.com/", ConfigurationName="YYhUploadService.CarryXmlToDbService")]
    public interface CarryXmlToDbService {
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        YYhUpload.YYhUploadService.handleFileResponse handleFile(YYhUpload.YYhUploadService.handleFile request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<YYhUpload.YYhUploadService.handleFileResponse> handleFileAsync(YYhUpload.YYhUploadService.handleFile request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(YYhUpload.YYhUploadService.Exception), Action="", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        YYhUpload.YYhUploadService.handleHistoryResponse handleHistory(YYhUpload.YYhUploadService.handleHistory request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<YYhUpload.YYhUploadService.handleHistoryResponse> handleHistoryAsync(YYhUpload.YYhUploadService.handleHistory request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(YYhUpload.YYhUploadService.Exception), Action="", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        YYhUpload.YYhUploadService.handleResponse handle(YYhUpload.YYhUploadService.handle request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<YYhUpload.YYhUploadService.handleResponse> handleAsync(YYhUpload.YYhUploadService.handle request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="handleFile", WrapperNamespace="http://webservice.entrance.si.neusoft.com/", IsWrapped=true)]
    public partial class handleFile {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.entrance.si.neusoft.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public handleFile() {
        }
        
        public handleFile(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="handleFileResponse", WrapperNamespace="http://webservice.entrance.si.neusoft.com/", IsWrapped=true)]
    public partial class handleFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.entrance.si.neusoft.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public handleFileResponse() {
        }
        
        public handleFileResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="handleHistory", WrapperNamespace="http://webservice.entrance.si.neusoft.com/", IsWrapped=true)]
    public partial class handleHistory {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.entrance.si.neusoft.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public handleHistory() {
        }
        
        public handleHistory(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="handleHistoryResponse", WrapperNamespace="http://webservice.entrance.si.neusoft.com/", IsWrapped=true)]
    public partial class handleHistoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.entrance.si.neusoft.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public handleHistoryResponse() {
        }
        
        public handleHistoryResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="handle", WrapperNamespace="http://webservice.entrance.si.neusoft.com/", IsWrapped=true)]
    public partial class handle {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.entrance.si.neusoft.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public handle() {
        }
        
        public handle(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="handleResponse", WrapperNamespace="http://webservice.entrance.si.neusoft.com/", IsWrapped=true)]
    public partial class handleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.entrance.si.neusoft.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public handleResponse() {
        }
        
        public handleResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CarryXmlToDbServiceChannel : YYhUpload.YYhUploadService.CarryXmlToDbService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CarryXmlToDbServiceClient : System.ServiceModel.ClientBase<YYhUpload.YYhUploadService.CarryXmlToDbService>, YYhUpload.YYhUploadService.CarryXmlToDbService {
        
        public CarryXmlToDbServiceClient() {
        }
        
        public CarryXmlToDbServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CarryXmlToDbServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarryXmlToDbServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarryXmlToDbServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YYhUpload.YYhUploadService.handleFileResponse YYhUpload.YYhUploadService.CarryXmlToDbService.handleFile(YYhUpload.YYhUploadService.handleFile request) {
            return base.Channel.handleFile(request);
        }
        
        public string handleFile(string arg0) {
            YYhUpload.YYhUploadService.handleFile inValue = new YYhUpload.YYhUploadService.handleFile();
            inValue.arg0 = arg0;
            YYhUpload.YYhUploadService.handleFileResponse retVal = ((YYhUpload.YYhUploadService.CarryXmlToDbService)(this)).handleFile(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YYhUpload.YYhUploadService.handleFileResponse> YYhUpload.YYhUploadService.CarryXmlToDbService.handleFileAsync(YYhUpload.YYhUploadService.handleFile request) {
            return base.Channel.handleFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<YYhUpload.YYhUploadService.handleFileResponse> handleFileAsync(string arg0) {
            YYhUpload.YYhUploadService.handleFile inValue = new YYhUpload.YYhUploadService.handleFile();
            inValue.arg0 = arg0;
            return ((YYhUpload.YYhUploadService.CarryXmlToDbService)(this)).handleFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YYhUpload.YYhUploadService.handleHistoryResponse YYhUpload.YYhUploadService.CarryXmlToDbService.handleHistory(YYhUpload.YYhUploadService.handleHistory request) {
            return base.Channel.handleHistory(request);
        }
        
        public string handleHistory(string arg0) {
            YYhUpload.YYhUploadService.handleHistory inValue = new YYhUpload.YYhUploadService.handleHistory();
            inValue.arg0 = arg0;
            YYhUpload.YYhUploadService.handleHistoryResponse retVal = ((YYhUpload.YYhUploadService.CarryXmlToDbService)(this)).handleHistory(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YYhUpload.YYhUploadService.handleHistoryResponse> YYhUpload.YYhUploadService.CarryXmlToDbService.handleHistoryAsync(YYhUpload.YYhUploadService.handleHistory request) {
            return base.Channel.handleHistoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<YYhUpload.YYhUploadService.handleHistoryResponse> handleHistoryAsync(string arg0) {
            YYhUpload.YYhUploadService.handleHistory inValue = new YYhUpload.YYhUploadService.handleHistory();
            inValue.arg0 = arg0;
            return ((YYhUpload.YYhUploadService.CarryXmlToDbService)(this)).handleHistoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YYhUpload.YYhUploadService.handleResponse YYhUpload.YYhUploadService.CarryXmlToDbService.handle(YYhUpload.YYhUploadService.handle request) {
            return base.Channel.handle(request);
        }
        
        public string handle(string arg0) {
            YYhUpload.YYhUploadService.handle inValue = new YYhUpload.YYhUploadService.handle();
            inValue.arg0 = arg0;
            YYhUpload.YYhUploadService.handleResponse retVal = ((YYhUpload.YYhUploadService.CarryXmlToDbService)(this)).handle(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YYhUpload.YYhUploadService.handleResponse> YYhUpload.YYhUploadService.CarryXmlToDbService.handleAsync(YYhUpload.YYhUploadService.handle request) {
            return base.Channel.handleAsync(request);
        }
        
        public System.Threading.Tasks.Task<YYhUpload.YYhUploadService.handleResponse> handleAsync(string arg0) {
            YYhUpload.YYhUploadService.handle inValue = new YYhUpload.YYhUploadService.handle();
            inValue.arg0 = arg0;
            return ((YYhUpload.YYhUploadService.CarryXmlToDbService)(this)).handleAsync(inValue);
        }
    }
}
